M48
; DRILL file {KiCad (6.0.2)} date Sat Mar 26 13:40:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-26T13:40:33+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.1161Y-2.7303
X6.3161Y-2.7317
T2
X5.5Y-3.0157
X5.5Y-5.1417
X6.7Y-3.0171
X6.7Y-5.1431
T0
M30
