M48
; DRILL file {KiCad (7.0.0)} date Tue Apr 25 12:57:29 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-25T12:57:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0827
%
G90
G05
T1
X5.8111Y-3.5768
X6.002Y-3.5768
T2
X5.7993Y-3.4575
X6.0138Y-3.4575
T3
X5.1226Y-5.3924
X6.4726Y-3.4524
X6.4726Y-5.3924
T0
M30
