M48
; DRILL file {KiCad (6.0.2-0)} date Tuesday, 29 March 2022 at 15:02:54
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-29T15:02:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.15Y-2.3748
X5.2Y-5.3748
X7.0Y-5.3748
X7.05Y-2.4248
T0
M30
